seed: 0
cuda: 0
world_size: 0
per_cpus: 0
max_epoch: 20
batch_size: 1
lead_time: 24
ratio: 0.9
resolution: 128
init_method: tcp://127.0.0.1:19111
model: Adas
rundir: ./configs/Adas/mask0.9_lead24h_res128
rank: 0
local_rank: 0
distributed: false
gpu: 0
cfg: ./configs/Adas/training_options.yaml
cfg_params:
  vnames: &id001
    single_level_vnames:
    - u10
    - v10
    - t2m
    - msl
    multi_level_vnames:
    - z
    - q
    - u
    - v
    - t
    hight_level_list:
    - 50
    - 100
    - 150
    - 200
    - 250
    - 300
    - 400
    - 500
    - 600
    - 700
    - 850
    - 925
    - 1000
  dataset:
    train:
      type: era5_npy_f32
      data_dir: ./data
      train_stride: 6
      file_stride: 6
      sample_stride: 1
      vnames: *id001
      length: 6
    valid:
      type: era5_npy_f32
      data_dir: ./data
      train_stride: 6
      file_stride: 6
      sample_stride: 1
      vnames: *id001
      length: 6
  dataloader:
    num_workers: 0
    pin_memory: true
    prefetch_factor: 2
    persistent_workers: true
  model:
    type: Adas
    params:
      img_size:
      - 69
      - 128
      - 256
      dim: 96
      patch_size:
      - 1
      - 2
      - 2
      window_size:
      - 2
      - 4
      - 8
      ape: true
    criterion: UnifyMAE
    optimizer:
      type: AdamW
      params:
        lr: 0.0001
        betas:
        - 0.9
        - 0.9
        weight_decay: 0.01
    lr_scheduler:
      type: OneCycleLR
      params:
        max_lr: 0.0001
        pct_start: 0.1
        anneal_strategy: cos
        div_factor: 100
        final_div_factor: 1000
