tensor_model_parallel_size: 1
pipeline_model_parallel_size: 1
resume: false
resume_from_config: false
seed: 0
cuda: 0
world_size: 32
per_cpus: 4
init_method: tcp://10.140.24.89:37758
outdir: /mnt/petrelfs/chenkang/code/wpredict/IF_WKP/lgunet_rpft_float32_13level_1inp
cfg: ./configs/era5/lgunet_rpft_float32_13level_1inp.yaml
desc: era5_lgunet_rpft_float32_13level_1inp
rank: 0
local_rank: 0
distributed: true
dist_backend: nccl
relative_checkpoint_dir: lgunet_rpft_float32_13level_1inp/world_size32-era5_lgunet_rpft_float32_13level_1inp
vnames: &id001
  single_level_vnames:
  - u10
  - v10
  - t2m
  - msl
  multi_level_vnames:
  - z
  - q
  - u
  - v
  - t
  hight_level_list:
  - 50
  - 100
  - 150
  - 200
  - 250
  - 300
  - 400
  - 500
  - 600
  - 700
  - 850
  - 925
  - 1000
dataset:
  train:
    type: era5_npy_f32
    data_dir: ./data
    train_stride: 6
    file_stride: 6
    sample_stride: 1
    vnames: *id001
  valid:
    type: era5_npy_f32
    data_dir: ./data
    train_stride: 6
    file_stride: 6
    sample_stride: 1
    vnames: *id001
dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true
model:
  type: VAE
  params:
    sigma: 0.3
    use_ceph: true
    save_best: Possloss
    encoder:
      img_size:
      - 128
      - 256
      patch_size:
      - 2
      - 2
      stride:
      - 2
      - 2
      inchans_list:
      - 4
      - 13
      - 13
      - 13
      - 13
      - 13
      outchans_list:
      - 4
      - 12
      - 12
      - 12
      - 12
      - 12
      in_chans: 138
      out_chans: 138
      enc_dim: 96
      embed_dim: 1152
      window_size: 4
      enc_depths:
      - 2
      - 2
      enc_heads:
      - 3
      - 6
      lg_depths:
      - 4
      - 4
      - 4
      lg_heads:
      - 6
      - 6
      - 6
      Weather_T: 1
      drop_path: 0.0
      use_checkpoint: false
      inp_length: 1
      use_mlp: false
    decoder:
      img_size:
      - 128
      - 256
      patch_size:
      - 2
      - 2
      stride:
      - 2
      - 2
      inchans_list:
      - 2
      - 6
      - 6
      - 6
      - 6
      - 6
      outchans_list:
      - 4
      - 13
      - 13
      - 13
      - 13
      - 13
      in_chans: 138
      out_chans: 138
      enc_dim: 96
      embed_dim: 1152
      window_size: 4
      enc_depths:
      - 2
      - 2
      enc_heads:
      - 3
      - 6
      lg_depths:
      - 4
      - 4
      - 4
      lg_heads:
      - 6
      - 6
      - 6
      Weather_T: 1
      drop_path: 0.0
      use_checkpoint: false
      inp_length: 1
      use_mlp: false
    metrics_list:
    - MAE
    - MSE
  optimizer:
    lgunet_all:
      type: AdamW
      params:
        lr: 5.0e-06
        betas:
        - 0.9
        - 0.9
  lr_scheduler:
    type: CosineLR
    params:
      by_step: true
      sched: cosine
      epochs: 10
      min_lr: 0.0
      warmup_lr: 1.0e-08
      warmup_epochs: 0
      lr_noise: null
      cooldown_epochs: 0
    extra_params:
      two_step_training: false
      loss_type: Possloss
      enabled_amp: false
      use_noise: false
      weight_begin_index: 4
      weight_end_index: 17
      weight_number: 0.1
      finetune_cycle_num: 3
      # checkpoint_dir: cephnew:s3://weatherbench/checkpoint
      whether_save_checkpoint: true
      save_best: false
      checkpoint_path: lgunet_all_float32_13level_1inp/world_size32-era5_lgunet_all_float32_13level_1inp/checkpoint_latest.pth
      replay_buff:
        inp_shape:
        - 69
        - 721
        - 1440
        max_size: 100
    constants_len: 0